name: Build

on: push

jobs:
    Build:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout
              uses: actions/checkout@v2.3.3
              with:
                  fetch-depth: 0

            - name: Install .NET Core
              uses: actions/setup-dotnet@v1.7.2
              with:
                  dotnet-version: "5.0.101"

            - name: Build
              run: dotnet build NotABug/NotABug/NotABug.csproj --configuration Release
              working-directory: ./
